### ISSUE TITLE
localName error on Chrome browser but works fine in other browsers using polyfill

### ISSUE THREAD

**Issue by kristianmandrup** [tony19/generator-polymer-init-2-x-app#3]
New 0.0.8 version works just fine in Firefox, Safari and Brave browsers.
I still get the error about missing `localName` on Chrome 58. 

I suspect it is trying to use `webcomponent-lite` polyfill when it should be using native support instead? Any ideas? Could be a bug in `webcomponents.js`? Your experience
I thought it might be a browser flag (experimental) problem, so reset all my flags but still... could it be an extension or just `webcomponent-lite` fucking up? Ah yes, the script include is now hardcoded

**Comment by tony19** [comment]
I can't reproduce the issue in Chrome 56 or 59. What's your environment?

> I suspect it is trying to use webcomponent-lite polyfill when it should be using native support instead?

You could easily test that theory by commenting out the `<script>` tag that brings in `webcomponentsjs`.

> could it be an extension or just webcomponent-lite fucking up?

To rule out extensions, try an incognito window (assuming you don't enable extensions there).

**Comment by kristianmandrup** [comment]
Tried re-configuring load script:

```js
      // Setup Polymer options
      window.Polymer = {
        dom: 'shadow',
        lazyRegister: 'max',
        useNativeCSSProperties: true
      };

      // Load webcomponentsjs polyfill if browser does not support native Web Components
      (() => {
        console.log('loading...')

        const onload = () => {
          // For native Imports, manually fire WebComponentsReady so user code
          // can use the same code path for native and polyfill'd imports.
          if (!window.HTMLImports) {
            document.dispatchEvent(
              new CustomEvent('WebComponentsReady', {bubbles: true})
            );
          }
        };

        const webComponentsSupported = (
          'registerElement' in document
          && 'import' in document.createElement('link')
          && 'content' in document.createElement('template')
        );

        console.log('webComponentsSupported', webComponentsSupported)

        if (!webComponentsSupported) {
          console.log('webComponents NOT supported, using polyfill')

          const script = document.createElement('script');
          script.async = true;
          script.src = 'bower_components/webcomponentsjs/webcomponents-lite.min.js';
          script.onload = onload;
          document.head.appendChild(script);
        } else {
          console.log('webComponents ARR supported, NOT using polyfill')
          onload();
        }
      })();
```

Browser console (Chrome 58)

```
loading...
(index):1 webComponentsSupported true
(index):1 webComponents ARR supported, NOT using polyfill
apply-shim.min.js:1 Uncaught TypeError: Cannot read property 'localName' of undefined
```

**Comment by kristianmandrup** [comment]
I will try a fresh Chrome Canary now

**Comment by kristianmandrup** [comment]
Yes, on a fresh Canary 59 it works beautifully with the above loading code :)
Perhaps you try a fresh Chrome 58 with default settings and no extensions. Cheers!

**Comment by kristianmandrup** [comment]
My environment: Mac OSX

**Comment by kristianmandrup** [comment]
I also got a 404 error inside main content area on the other browsers with initial 0.0.8 version that has hard coded script tag only. But the rest of the app displayed just fine (routing error?!)

**Comment by kristianmandrup** [comment]
In Firefox I get this error using the load script:

```
The resource from “http://127.0.0.1:8081/components/polymer-starter-kit/bower_components/webcomponentsjs/webcomponents-lite.min.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).
```

**Comment by kristianmandrup** [comment]
And in Safari

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) 
http://127.0.0.1:8081/components/polymer-starter-kit/bower_components/webcomponentsjs/webcomponents-lite.min.js
(webcomponents-lite.min.js, line 0)
```

Looks like `bower_components` is not added as a public asset folders on the server?

**Comment by kristianmandrup** [comment]
After changing it to `webcomponents-lite.js` it works in Firefox, Safari and Brave

**Comment by kristianmandrup** [comment]
So by now, I think my only problem is a misbehaving Extension on my Chrome 58
