### ISSUE TITLE
Is this project still working?

### ISSUE THREAD

**Issue by santanafabio** [tony19/generator-polymer-init-2-x-app#5]
Hey buddy, is this project updated? Cause the building is falling to me!

**Comment by tony19** [comment]
How is the build failing for you?

FYI, PSK 3.0 (recently released now supports Polymer 2.0), and the Polymer CLI is currently being updated to use it, so this repo is about to be removed.

**Comment by santanafabio** [comment]
Yeah, I discover my mistake.
Thx and sorry
